/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LootSplitRouteImport } from './routes/loot-split'
import { Route as IndexRouteImport } from './routes/index'

const LootSplitRoute = LootSplitRouteImport.update({
  id: '/loot-split',
  path: '/loot-split',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loot-split': typeof LootSplitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loot-split': typeof LootSplitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/loot-split': typeof LootSplitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/loot-split'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/loot-split'
  id: '__root__' | '/' | '/loot-split'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LootSplitRoute: typeof LootSplitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/loot-split': {
      id: '/loot-split'
      path: '/loot-split'
      fullPath: '/loot-split'
      preLoaderRoute: typeof LootSplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LootSplitRoute: LootSplitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
